image: python:3.9


variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"
  PLATFORMIO_CACHE_DIR: "$CI_PROJECT_DIR/.platformio-cache"

cache:
  paths:
    - .pip-cache/
    - .platformio-cache/

stages:
 - build

before_script:
  - "pip install -U platformio"
  - "pio lib install 'adafruit/Adafruit MAX31865 library'"
  - "pio lib install 'spacehuhn/SimpleCLI'"
  - "pio lib install 'bodmer/TFT_eSPI'"
  - "pio lib install 'lennarthennigs/Button2@^1.6.5'"
  - "cp User_Setup_Select.h .pio/libdeps/esp32dev/TFT_eSPI/"

job:
    stage: build
    tags:
      - docker
    script: "pio run"
