image: python:3.9


variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"
  PLATFORMIO_CACHE_DIR: "$CI_PROJECT_DIR/.platformio-cache"

cache:
  paths:
    - .pip-cache/
    - .platformio-cache/

stages:
 - build

before_script:
  - "pip install -U platformio"
  - "pio lib install 'spacehuhn/SimpleCLI'"

job:
    stage: build
    tags:
      - docker
    script: "pio run"
